version: '2'
services:
  db:
    container_name: chatty_db
    image: rethinkdb
    ports:
     - "28015:28015"
    volumes:
     - ./data:/data

  backend:
    container_name: chatty_backend
    build: './backend'
    volumes:
      - './backend:/app'
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    container_name: chatty_frontend
    build: './frontend'
    volumes:
      - './frontend:/app'
    ports:
      - "8080:8080"

  nginx:
    container_name: chatty_nginx
    restart: always
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
